- hosts: ankeborg
  become: true
  vars:
    mail_hostname: "{{ inventory_hostname }}"
    canonical_name: "{{ inventory_hostname_short }}.mynet.\
      example.com"
    relay_user: xxx
    relay_password: yyy
    external_email_address: me@example.com

  roles:
    - jackbenny.postfix

