- hosts: ankeborg
  become: true
  vars:
    mail_hostname: "{{ inventory_hostname }}"
    canonical_name: "{{ inventory_hostname_short }}.nixnet.\
      example.tld"

  roles:
    - base-v2
    - postfix-v4

