- name: Uppdatera systemen
  become: true
  serial: 1
  hosts: ankeborg
  tasks:
    - name: Uppdatera Debian-baserade system
      when: ansible_os_family == 'Debian'
      apt:
        update_cache: yes
        upgrade: dist
      notify: Starta om systemet

    - name: Uppdatera RedHat-baserade system
      when: ansible_os_family == 'RedHat' 
      dnf:
        name:  "*"
        state: latest
        update_cache: yes
        update_only: yes
      notify: Starta om systemet

  handlers:
    - name: Starta om systemet
      reboot:
        connect_timeout: 5
        reboot_timeout: 600
        post_reboot_delay: 30
        test_command: whoami

