- name: Aktivera Apache i Debian
  tags:
    - apache
    - systemd
  systemd:
    name: apache2
    enabled: yes
    state: started

- name: Aktivera Apache i RedHat
  tags:
    - apache
    - systemd
  systemd:
    name: httpd
    enabled: yes
    state: started

