- name: Aktivera Apache i Debian
  tags:
    - apache
    - systemd
  when: ansible_os_family == 'Debian'
  systemd:
    name: apache2
    enabled: yes
    state: started

- name: Aktivera Apache i RedHat
  tags:
    - apache
    - systemd
  when: ansible_os_family == 'RedHat'
  systemd:
    name: httpd
    enabled: yes
    state: started

